import {
  User,
  CandidateProfile,
  HRProfile,
  Job,
  Application,
  ChatConversation,
  ChatMessage,
} from "./types";

// Mock Users
export const mockUsers: User[] = [
  {
    id: "user-1",
    email: "john.doe@example.com",
    password: "password123",
    name: "John Doe",
    role: "candidate",
    createdAt: new Date("2024-01-15"),
  },
  {
    id: "user-2",
    email: "jane.smith@example.com",
    password: "password123",
    name: "Jane Smith",
    role: "candidate",
    createdAt: new Date("2024-02-10"),
  },
  {
    id: "user-3",
    email: "mike.johnson@example.com",
    password: "password123",
    name: "Mike Johnson",
    role: "candidate",
    createdAt: new Date("2024-01-20"),
  },
  {
    id: "user-4",
    email: "sarah.wilson@example.com",
    password: "password123",
    name: "Sarah Wilson",
    role: "candidate",
    createdAt: new Date("2024-02-05"),
  },
  {
    id: "user-5",
    email: "alex.brown@example.com",
    password: "password123",
    name: "Alex Brown",
    role: "candidate",
    createdAt: new Date("2024-02-20"),
  },
  {
    id: "user-6",
    email: "emma.davis@example.com",
    password: "password123",
    name: "Emma Davis",
    role: "candidate",
    createdAt: new Date("2024-01-25"),
  },
  {
    id: "user-7",
    email: "hr.manager@techcorp.com",
    password: "password123",
    name: "Lisa Chen",
    role: "hr",
    createdAt: new Date("2023-12-01"),
  },
];

// Mock Candidate Profiles
export const mockCandidateProfiles: CandidateProfile[] = [
  {
    id: "candidate-1",
    userId: "user-1",
    fullName: "John Doe",
    email: "john.doe@example.com",
    phone: "+1 (555) 123-4567",
    location: "San Francisco, CA",
    yearsOfExperience: 5,
    skills: ["React", "TypeScript", "Node.js", "SQL", "AWS"],
    education: [
      {
        id: "edu-1",
        institution: "UC Berkeley",
        degree: "Bachelor of Science",
        field: "Computer Science",
        startYear: 2015,
        endYear: 2019,
        isCurrent: false,
      },
    ],
    portfolio: "https://johndoe.dev",
    linkedIn: "https://linkedin.com/in/johndoe",
    github: "https://github.com/johndoe",
    bio: "Full-stack developer passionate about building scalable applications",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15"),
  },
  {
    id: "candidate-2",
    userId: "user-2",
    fullName: "Jane Smith",
    email: "jane.smith@example.com",
    phone: "+1 (555) 234-5678",
    location: "Austin, TX",
    yearsOfExperience: 7,
    skills: ["Python", "Django", "PostgreSQL", "Docker", "Kubernetes"],
    education: [
      {
        id: "edu-2",
        institution: "University of Texas",
        degree: "Bachelor of Science",
        field: "Software Engineering",
        startYear: 2014,
        endYear: 2018,
        isCurrent: false,
      },
    ],
    portfolio: "https://janesmith.dev",
    linkedIn: "https://linkedin.com/in/janesmith",
    github: "https://github.com/janesmith",
    bio: "Backend engineer with expertise in cloud infrastructure",
    createdAt: new Date("2024-02-10"),
    updatedAt: new Date("2024-02-10"),
  },
  {
    id: "candidate-3",
    userId: "user-3",
    fullName: "Mike Johnson",
    email: "mike.johnson@example.com",
    phone: "+1 (555) 345-6789",
    location: "New York, NY",
    yearsOfExperience: 4,
    skills: ["Vue.js", "JavaScript", "CSS", "PHP", "MySQL"],
    education: [
      {
        id: "edu-3",
        institution: "Columbia University",
        degree: "Bachelor of Science",
        field: "Information Technology",
        startYear: 2016,
        endYear: 2020,
        isCurrent: false,
      },
    ],
    portfolio: "https://mikejohnson.dev",
    linkedIn: "https://linkedin.com/in/mikejohnson",
    bio: "Frontend-focused developer with strong UI/UX sensibilities",
    createdAt: new Date("2024-01-20"),
    updatedAt: new Date("2024-01-20"),
  },
  {
    id: "candidate-4",
    userId: "user-4",
    fullName: "Sarah Wilson",
    email: "sarah.wilson@example.com",
    phone: "+1 (555) 456-7890",
    location: "Seattle, WA",
    yearsOfExperience: 8,
    skills: ["Java", "Spring Boot", "Microservices", "AWS", "MongoDB"],
    education: [
      {
        id: "edu-4",
        institution: "University of Washington",
        degree: "Master of Science",
        field: "Computer Science",
        startYear: 2013,
        endYear: 2015,
        isCurrent: false,
      },
    ],
    portfolio: "https://sarahwilson.dev",
    linkedIn: "https://linkedin.com/in/sarahwilson",
    github: "https://github.com/sarahwilson",
    bio: "Senior developer with expertise in enterprise Java applications",
    createdAt: new Date("2024-02-05"),
    updatedAt: new Date("2024-02-05"),
  },
  {
    id: "candidate-5",
    userId: "user-5",
    fullName: "Alex Brown",
    email: "alex.brown@example.com",
    phone: "+1 (555) 567-8901",
    location: "Boston, MA",
    yearsOfExperience: 3,
    skills: ["React", "Next.js", "Tailwind CSS", "GraphQL", "Firebase"],
    education: [
      {
        id: "edu-5",
        institution: "MIT",
        degree: "Bachelor of Science",
        field: "Computer Science",
        startYear: 2018,
        endYear: 2022,
        isCurrent: false,
      },
    ],
    portfolio: "https://alexbrown.dev",
    linkedIn: "https://linkedin.com/in/alexbrown",
    github: "https://github.com/alexbrown",
    bio: "Recent graduate with focus on modern web technologies",
    createdAt: new Date("2024-02-20"),
    updatedAt: new Date("2024-02-20"),
  },
  {
    id: "candidate-6",
    userId: "user-6",
    fullName: "Emma Davis",
    email: "emma.davis@example.com",
    phone: "+1 (555) 678-9012",
    location: "Denver, CO",
    yearsOfExperience: 6,
    skills: ["React", "Python", "AWS", "DevOps", "CI/CD"],
    education: [
      {
        id: "edu-6",
        institution: "University of Colorado",
        degree: "Bachelor of Science",
        field: "Computer Science",
        startYear: 2015,
        endYear: 2019,
        isCurrent: false,
      },
    ],
    portfolio: "https://emmadavis.dev",
    linkedIn: "https://linkedin.com/in/emmadavis",
    github: "https://github.com/emmadavis",
    bio: "Full-stack engineer passionate about automation and infrastructure",
    createdAt: new Date("2024-01-25"),
    updatedAt: new Date("2024-01-25"),
  },
];

// Mock HR Profile
export const mockHRProfiles: HRProfile[] = [
  {
    id: "hr-1",
    userId: "user-7",
    companyName: "TechCorp Inc",
    companySize: "500-1000",
    department: "Engineering",
    createdAt: new Date("2023-12-01"),
    updatedAt: new Date("2023-12-01"),
  },
];

// Mock Jobs
export const mockJobs: Job[] = [
  {
    id: "job-1",
    hrId: "hr-1",
    title: "Senior React Developer",
    description:
      "We are looking for an experienced React developer to lead our frontend team. You will work on building scalable, high-performance web applications.",
    department: "Engineering",
    location: "San Francisco, CA",
    requiredSkills: ["React", "TypeScript", "Node.js"],
    minExperience: 4,
    minEducation: "Bachelor's degree",
    salaryRange: { min: 120000, max: 180000 },
    status: "active",
    createdAt: new Date("2024-01-01"),
    applicantCount: 12,
  },
  {
    id: "job-2",
    hrId: "hr-1",
    title: "Full-Stack Developer",
    description:
      "Join our team to build innovative products using modern web technologies. Experience with both frontend and backend development required.",
    department: "Engineering",
    location: "Austin, TX",
    requiredSkills: ["React", "Python", "Docker"],
    minExperience: 3,
    minEducation: "Bachelor's degree",
    salaryRange: { min: 100000, max: 150000 },
    status: "active",
    createdAt: new Date("2024-01-05"),
    applicantCount: 8,
  },
  {
    id: "job-3",
    hrId: "hr-1",
    title: "DevOps Engineer",
    description:
      "Help us build and maintain our cloud infrastructure. We are looking for someone with hands-on experience in AWS and Kubernetes.",
    department: "Engineering",
    location: "Remote",
    requiredSkills: ["AWS", "Kubernetes", "Docker"],
    minExperience: 5,
    minEducation: "Bachelor's degree",
    salaryRange: { min: 130000, max: 170000 },
    status: "active",
    createdAt: new Date("2024-01-10"),
    applicantCount: 6,
  },
];

// Mock Applications
export const mockApplications: Application[] = [
  {
    id: "app-1",
    jobId: "job-1",
    candidateId: "candidate-1",
    status: "shortlisted",
    appliedAt: new Date("2024-02-15"),
    shortlistedAt: new Date("2024-02-20"),
  },
  {
    id: "app-2",
    jobId: "job-1",
    candidateId: "candidate-2",
    status: "applied",
    appliedAt: new Date("2024-02-18"),
  },
  {
    id: "app-3",
    jobId: "job-1",
    candidateId: "candidate-3",
    status: "rejected",
    appliedAt: new Date("2024-02-10"),
    rejectedAt: new Date("2024-02-22"),
  },
  {
    id: "app-4",
    jobId: "job-2",
    candidateId: "candidate-4",
    status: "applied",
    appliedAt: new Date("2024-02-16"),
  },
  {
    id: "app-5",
    jobId: "job-2",
    candidateId: "candidate-5",
    status: "shortlisted",
    appliedAt: new Date("2024-02-14"),
    shortlistedAt: new Date("2024-02-21"),
  },
  {
    id: "app-6",
    jobId: "job-3",
    candidateId: "candidate-6",
    status: "applied",
    appliedAt: new Date("2024-02-19"),
  },
];

// Mock Chat Conversations
export const mockChatConversations: ChatConversation[] = [
  {
    id: "chat-1",
    hrId: "hr-1",
    candidateId: "candidate-1",
    jobId: "job-1",
    applicationId: "app-1",
    createdAt: new Date("2024-02-20"),
    updatedAt: new Date("2024-02-22"),
    lastMessage: "Thanks for the opportunity! I'm excited to learn more.",
  },
];

// Mock Chat Messages
export const mockChatMessages: ChatMessage[] = [
  {
    id: "msg-1",
    conversationId: "chat-1",
    senderId: "user-7",
    senderRole: "hr",
    message:
      "Hi John! Congratulations on being shortlisted for the Senior React Developer position.",
    timestamp: new Date("2024-02-20 10:30"),
    read: true,
  },
  {
    id: "msg-2",
    conversationId: "chat-1",
    senderId: "user-1",
    senderRole: "candidate",
    message: "Thank you so much! I'm very interested in this opportunity.",
    timestamp: new Date("2024-02-20 14:15"),
    read: true,
  },
  {
    id: "msg-3",
    conversationId: "chat-1",
    senderId: "user-7",
    senderRole: "hr",
    message:
      "We'd like to schedule an interview. Are you available next week?",
    timestamp: new Date("2024-02-21 09:00"),
    read: true,
  },
  {
    id: "msg-4",
    conversationId: "chat-1",
    senderId: "user-1",
    senderRole: "candidate",
    message:
      "Yes, I am! I'm flexible with my schedule. What times work best for you?",
    timestamp: new Date("2024-02-21 16:45"),
    read: true,
  },
  {
    id: "msg-5",
    conversationId: "chat-1",
    senderId: "user-7",
    senderRole: "hr",
    message: "Great! How about Tuesday at 2 PM PST?",
    timestamp: new Date("2024-02-22 10:00"),
    read: true,
  },
  {
    id: "msg-6",
    conversationId: "chat-1",
    senderId: "user-1",
    senderRole: "candidate",
    message:
      "Perfect! I'll be there. Thanks for the opportunity! I'm excited to learn more.",
    timestamp: new Date("2024-02-22 11:30"),
    read: true,
  },
];
